import Link from "next/link";
import AuthProvider from "./AuthProvider";
import NavMenu from "./NavMenu";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const myFont = Open_Sans({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={myFont.className}>
          <div className="container">
            <NavMenu />
            <main>{children}</main>
            <footer>
              <p>
                Created by Tanaka for
                <Link href="https://techpal.co.za">TechPal</Link>
              </p>
              <ul>
                <li>
                  <Link href={"/about"}>About</Link>
                </li>{" "}
                |
                <li>
                  <Link href={"https://www.youtube.com"}>YouTube</Link>
                </li>{" "}
                |
                <li>
                  <Link href={"/login"}>Source Code</Link>
                </li>{" "}
                |
                <li>
                  <Link href={"https://nextjs.org"}>NextJS Docs</Link>
                </li>
              </ul>
            </footer>
          </div>
        </body>
      </html>
    </AuthProvider>
  );
}
